/**
 * @fileoverview gRPC-Web generated client stub for auth
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: auth.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.auth = require('./auth_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.auth.AuthServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.auth.AuthServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.BasicLoginRequest,
 *   !proto.auth.BasicLoginResponse>}
 */
const methodDescriptor_AuthService_BasicLogin = new grpc.web.MethodDescriptor(
  '/auth.AuthService/BasicLogin',
  grpc.web.MethodType.UNARY,
  proto.auth.BasicLoginRequest,
  proto.auth.BasicLoginResponse,
  /**
   * @param {!proto.auth.BasicLoginRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.BasicLoginResponse.deserializeBinary
);


/**
 * @param {!proto.auth.BasicLoginRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.BasicLoginResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.BasicLoginResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.AuthServiceClient.prototype.basicLogin =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.AuthService/BasicLogin',
      request,
      metadata || {},
      methodDescriptor_AuthService_BasicLogin,
      callback);
};


/**
 * @param {!proto.auth.BasicLoginRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.BasicLoginResponse>}
 *     Promise that resolves to the response
 */
proto.auth.AuthServicePromiseClient.prototype.basicLogin =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.AuthService/BasicLogin',
      request,
      metadata || {},
      methodDescriptor_AuthService_BasicLogin);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.VerifyJWTRequest,
 *   !proto.auth.VerifyJWTResponse>}
 */
const methodDescriptor_AuthService_VerifyJWT = new grpc.web.MethodDescriptor(
  '/auth.AuthService/VerifyJWT',
  grpc.web.MethodType.UNARY,
  proto.auth.VerifyJWTRequest,
  proto.auth.VerifyJWTResponse,
  /**
   * @param {!proto.auth.VerifyJWTRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.VerifyJWTResponse.deserializeBinary
);


/**
 * @param {!proto.auth.VerifyJWTRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.VerifyJWTResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.VerifyJWTResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.AuthServiceClient.prototype.verifyJWT =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.AuthService/VerifyJWT',
      request,
      metadata || {},
      methodDescriptor_AuthService_VerifyJWT,
      callback);
};


/**
 * @param {!proto.auth.VerifyJWTRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.VerifyJWTResponse>}
 *     Promise that resolves to the response
 */
proto.auth.AuthServicePromiseClient.prototype.verifyJWT =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.AuthService/VerifyJWT',
      request,
      metadata || {},
      methodDescriptor_AuthService_VerifyJWT);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.VerifyAPIKeyRequest,
 *   !proto.auth.VerifyAPIKeyResponse>}
 */
const methodDescriptor_AuthService_VerifyAPIKey = new grpc.web.MethodDescriptor(
  '/auth.AuthService/VerifyAPIKey',
  grpc.web.MethodType.UNARY,
  proto.auth.VerifyAPIKeyRequest,
  proto.auth.VerifyAPIKeyResponse,
  /**
   * @param {!proto.auth.VerifyAPIKeyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.VerifyAPIKeyResponse.deserializeBinary
);


/**
 * @param {!proto.auth.VerifyAPIKeyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.VerifyAPIKeyResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.VerifyAPIKeyResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.AuthServiceClient.prototype.verifyAPIKey =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.AuthService/VerifyAPIKey',
      request,
      metadata || {},
      methodDescriptor_AuthService_VerifyAPIKey,
      callback);
};


/**
 * @param {!proto.auth.VerifyAPIKeyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.VerifyAPIKeyResponse>}
 *     Promise that resolves to the response
 */
proto.auth.AuthServicePromiseClient.prototype.verifyAPIKey =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.AuthService/VerifyAPIKey',
      request,
      metadata || {},
      methodDescriptor_AuthService_VerifyAPIKey);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.GetPersonnelDataRequest,
 *   !proto.auth.GetPersonnelDataResponse>}
 */
const methodDescriptor_AuthService_GetPersonnelData = new grpc.web.MethodDescriptor(
  '/auth.AuthService/GetPersonnelData',
  grpc.web.MethodType.UNARY,
  proto.auth.GetPersonnelDataRequest,
  proto.auth.GetPersonnelDataResponse,
  /**
   * @param {!proto.auth.GetPersonnelDataRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.GetPersonnelDataResponse.deserializeBinary
);


/**
 * @param {!proto.auth.GetPersonnelDataRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.GetPersonnelDataResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.GetPersonnelDataResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.AuthServiceClient.prototype.getPersonnelData =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.AuthService/GetPersonnelData',
      request,
      metadata || {},
      methodDescriptor_AuthService_GetPersonnelData,
      callback);
};


/**
 * @param {!proto.auth.GetPersonnelDataRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.GetPersonnelDataResponse>}
 *     Promise that resolves to the response
 */
proto.auth.AuthServicePromiseClient.prototype.getPersonnelData =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.AuthService/GetPersonnelData',
      request,
      metadata || {},
      methodDescriptor_AuthService_GetPersonnelData);
};


module.exports = proto.auth;

