// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: api.proto

package api_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// APIServiceClient is the client API for APIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APIServiceClient interface {
	RegisterAuthorizedAPI(ctx context.Context, in *RegisterAuthorizedAPIRequest, opts ...grpc.CallOption) (*RegisterAuthorizedAPIResponse, error)
	RollingAPIKey(ctx context.Context, in *RollingAPIKeyRequest, opts ...grpc.CallOption) (*RollingAPIKeyResponse, error)
	DisableAPI(ctx context.Context, in *DisableAPIRequest, opts ...grpc.CallOption) (*APIServiceGenericResponse, error)
	GetRegisteredAPI(ctx context.Context, in *GetRegisteredAPIRequest, opts ...grpc.CallOption) (*GetRegisteredAPIResponse, error)
}

type aPIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIServiceClient(cc grpc.ClientConnInterface) APIServiceClient {
	return &aPIServiceClient{cc}
}

func (c *aPIServiceClient) RegisterAuthorizedAPI(ctx context.Context, in *RegisterAuthorizedAPIRequest, opts ...grpc.CallOption) (*RegisterAuthorizedAPIResponse, error) {
	out := new(RegisterAuthorizedAPIResponse)
	err := c.cc.Invoke(ctx, "/auth.APIService/RegisterAuthorizedAPI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) RollingAPIKey(ctx context.Context, in *RollingAPIKeyRequest, opts ...grpc.CallOption) (*RollingAPIKeyResponse, error) {
	out := new(RollingAPIKeyResponse)
	err := c.cc.Invoke(ctx, "/auth.APIService/RollingAPIKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) DisableAPI(ctx context.Context, in *DisableAPIRequest, opts ...grpc.CallOption) (*APIServiceGenericResponse, error) {
	out := new(APIServiceGenericResponse)
	err := c.cc.Invoke(ctx, "/auth.APIService/DisableAPI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetRegisteredAPI(ctx context.Context, in *GetRegisteredAPIRequest, opts ...grpc.CallOption) (*GetRegisteredAPIResponse, error) {
	out := new(GetRegisteredAPIResponse)
	err := c.cc.Invoke(ctx, "/auth.APIService/GetRegisteredAPI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServiceServer is the server API for APIService service.
// All implementations must embed UnimplementedAPIServiceServer
// for forward compatibility
type APIServiceServer interface {
	RegisterAuthorizedAPI(context.Context, *RegisterAuthorizedAPIRequest) (*RegisterAuthorizedAPIResponse, error)
	RollingAPIKey(context.Context, *RollingAPIKeyRequest) (*RollingAPIKeyResponse, error)
	DisableAPI(context.Context, *DisableAPIRequest) (*APIServiceGenericResponse, error)
	GetRegisteredAPI(context.Context, *GetRegisteredAPIRequest) (*GetRegisteredAPIResponse, error)
	mustEmbedUnimplementedAPIServiceServer()
}

// UnimplementedAPIServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAPIServiceServer struct {
}

func (UnimplementedAPIServiceServer) RegisterAuthorizedAPI(context.Context, *RegisterAuthorizedAPIRequest) (*RegisterAuthorizedAPIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAuthorizedAPI not implemented")
}
func (UnimplementedAPIServiceServer) RollingAPIKey(context.Context, *RollingAPIKeyRequest) (*RollingAPIKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollingAPIKey not implemented")
}
func (UnimplementedAPIServiceServer) DisableAPI(context.Context, *DisableAPIRequest) (*APIServiceGenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableAPI not implemented")
}
func (UnimplementedAPIServiceServer) GetRegisteredAPI(context.Context, *GetRegisteredAPIRequest) (*GetRegisteredAPIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegisteredAPI not implemented")
}
func (UnimplementedAPIServiceServer) mustEmbedUnimplementedAPIServiceServer() {}

// UnsafeAPIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIServiceServer will
// result in compilation errors.
type UnsafeAPIServiceServer interface {
	mustEmbedUnimplementedAPIServiceServer()
}

func RegisterAPIServiceServer(s grpc.ServiceRegistrar, srv APIServiceServer) {
	s.RegisterService(&APIService_ServiceDesc, srv)
}

func _APIService_RegisterAuthorizedAPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAuthorizedAPIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).RegisterAuthorizedAPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.APIService/RegisterAuthorizedAPI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).RegisterAuthorizedAPI(ctx, req.(*RegisterAuthorizedAPIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_RollingAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollingAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).RollingAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.APIService/RollingAPIKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).RollingAPIKey(ctx, req.(*RollingAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_DisableAPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableAPIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).DisableAPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.APIService/DisableAPI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).DisableAPI(ctx, req.(*DisableAPIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetRegisteredAPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRegisteredAPIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetRegisteredAPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.APIService/GetRegisteredAPI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetRegisteredAPI(ctx, req.(*GetRegisteredAPIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// APIService_ServiceDesc is the grpc.ServiceDesc for APIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var APIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.APIService",
	HandlerType: (*APIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAuthorizedAPI",
			Handler:    _APIService_RegisterAuthorizedAPI_Handler,
		},
		{
			MethodName: "RollingAPIKey",
			Handler:    _APIService_RollingAPIKey_Handler,
		},
		{
			MethodName: "DisableAPI",
			Handler:    _APIService_DisableAPI_Handler,
		},
		{
			MethodName: "GetRegisteredAPI",
			Handler:    _APIService_GetRegisteredAPI_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
